name: Run Reports

on:
  workflow_dispatch:
  schedule:
    - cron: "50 10,20 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACTION_BOT}}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0
      - name: discovery
        run: env
      - name: gem install
        shell: bash
        run: gem install kramdown kramdown-asciidoc asciidoctor asciidoctor-pdf asciidoctor-rouge hexapdf rouge
